// Gerçek, ölçülü ve denenmiş tarifler. Sunucu ilk kez açıldığında,
// veritabanında hiç tarif yoksa (veya bu seed'ler eksikse) otomatik
// olarak eklenir; elle bir şey yapmaya gerek yoktur.

export type SeedIngredient = { name: string; amount: number | null; unit: string; scalable: boolean };

export type SeedRecipe = {
  category: string;
  title: string;
  summary: string;
  tip: string;
  servings: number;
  prepMinutes: number;
  cookMinutes: number;
  ingredients: SeedIngredient[];
  steps: string[];
};

export const seedRecipes: SeedRecipe[] = [
  // ---- KAHVALTI ----
  {
    category: "Kahvaltı",
    title: "Menemen",
    summary: "Domates, biber ve yumurtayla yapılan klasik Türk kahvaltı yemeği.",
    tip: "Domatesleri önce kendi suyunda pişirip biraz azaltın, yumurta daha sulu olmasın diye.",
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      { name: "domates", amount: 3, unit: "adet", scalable: true },
      { name: "yeşil sivri biber", amount: 2, unit: "adet", scalable: true },
      { name: "yumurta", amount: 4, unit: "adet", scalable: true },
      { name: "zeytinyağı veya tereyağı", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "tuz", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "pul biber", amount: 0.5, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Domatesleri rendeleyin veya küçük küpler halinde doğrayın. Biberleri ince ince doğrayın.",
      "Tavada yağı kızdırın, biberleri ekleyip 3-4 dakika kavurun.",
      "Domatesleri ekleyip suyunu çekene kadar orta ateşte 8-10 dakika pişirin.",
      "Tuz ve pul biberi ekleyin, yumurtaları kırıp tavaya dökün.",
      "Yumurtalar isteğinize göre pişene kadar hafifçe karıştırıp sıcak servis edin.",
    ],
  },
  {
    category: "Kahvaltı",
    title: "Sucuklu Yumurta",
    summary: "Az malzemeyle, hızlı hazırlanan doyurucu bir kahvaltılık.",
    tip: "Sucuğu önce yağsız kavurup kendi yağını çıkarmasını bekleyin, sonra yumurtayı ekleyin.",
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 10,
    ingredients: [
      { name: "sucuk", amount: 150, unit: "gram", scalable: true },
      { name: "yumurta", amount: 4, unit: "adet", scalable: true },
      { name: "tereyağı", amount: 1, unit: "yemek kaşığı", scalable: true },
    ],
    steps: [
      "Sucuğu ince dilimler halinde kesin.",
      "Tavaya tereyağını alın, sucukları ekleyip kendi yağını salana kadar orta ateşte kavurun (5 dk).",
      "Yumurtaları kırıp tavaya ekleyin, tuz gerekirse azıcık ekleyin (sucuk zaten tuzludur).",
      "Yumurta akı pişip sarısı kıvamında kalınca ocaktan alıp sıcak servis edin.",
    ],
  },
  {
    category: "Kahvaltı",
    title: "Peynirli Omlet",
    summary: "Yumuşacık, kabarık, peynir dolgulu klasik omlet.",
    tip: "Omleti pişirirken tavayı hareket ettirip kenarlardan ortaya doğru toplarsanız daha kabarık olur.",
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 6,
    ingredients: [
      { name: "yumurta", amount: 3, unit: "adet", scalable: true },
      { name: "beyaz peynir", amount: 50, unit: "gram", scalable: true },
      { name: "süt", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "tereyağı", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "tuz", amount: 1, unit: "tutam", scalable: false },
    ],
    steps: [
      "Yumurtaları süt ve tuzla birlikte çatalla iyice çırpın.",
      "Tavada tereyağını kızdırın, yumurta karışımını dökün.",
      "Kenarları pişmeye başlayınca ufalanmış peyniri üzerine serpin.",
      "Yarısını üzerine katlayıp az pişmiş kısmın da pişmesini sağlayın, sıcak servis edin.",
    ],
  },

  // ---- ÇORBALAR ----
  {
    category: "Çorbalar",
    title: "Mercimek Çorbası",
    summary: "Kırmızı mercimekle yapılan, pürüzsüz kıvamlı klasik Türk çorbası.",
    tip: "Çorbayı blenderdan geçirmeden önce havuç ve soğanın iyice yumuşadığından emin olun.",
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    ingredients: [
      { name: "kırmızı mercimek", amount: 1, unit: "su bardağı", scalable: true },
      { name: "soğan", amount: 1, unit: "adet", scalable: true },
      { name: "havuç", amount: 1, unit: "adet", scalable: true },
      { name: "patates", amount: 1, unit: "adet", scalable: true },
      { name: "un", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "tereyağı", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "su veya et suyu", amount: 6, unit: "su bardağı", scalable: true },
      { name: "tuz", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "pul biber (üzeri için)", amount: 1, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Soğanı, havucu ve patatesi küçük küpler halinde doğrayın.",
      "Tencerede tereyağını eritin, soğanları pembeleşene kadar kavurun.",
      "Unu ekleyip 1 dakika kavurun, ardından havuç, patates ve yıkanmış mercimeği ekleyin.",
      "Su veya et suyunu ilave edip kaynatın, kısık ateşte sebzeler ve mercimek yumuşayana kadar (25 dk) pişirin.",
      "Blenderdan geçirip pürüzsüz hale getirin, tuzunu ayarlayın.",
      "Servis ederken üzerine tereyağında kavrulmuş pul biber gezdirin.",
    ],
  },
  {
    category: "Çorbalar",
    title: "Ezogelin Çorbası",
    summary: "Kırmızı mercimek, bulgur ve pirinçle yapılan baharatlı, doyurucu çorba.",
    tip: "Naneyi servis anında değil, pişirmenin son dakikalarında eklerseniz aroması daha iyi karışır.",
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    ingredients: [
      { name: "kırmızı mercimek", amount: 0.5, unit: "su bardağı", scalable: true },
      { name: "pirinç", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "ince bulgur", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "soğan", amount: 1, unit: "adet", scalable: true },
      { name: "salça (domates)", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "tereyağı", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "su", amount: 7, unit: "su bardağı", scalable: true },
      { name: "kurutulmuş nane", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "pul biber", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "tuz", amount: 1, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Soğanı ince ince doğrayın. Tencerede tereyağıyla pembeleşene kadar kavurun.",
      "Salçayı ekleyip 1-2 dakika kavurun, ardından pul biberi ilave edin.",
      "Yıkanmış mercimek, pirinç ve bulguru ekleyip su ile birlikte kaynatın.",
      "Kısık ateşte, malzemeler tamamen yumuşayana kadar 25-30 dakika pişirin, ara sıra karıştırın.",
      "Tuz ve naneyi ekleyip 5 dakika daha kaynatın, sıcak servis edin.",
    ],
  },
  {
    category: "Çorbalar",
    title: "Yayla Çorbası",
    summary: "Yoğurt ve nane ile yapılan hafif, ferahlatıcı bir çorba.",
    tip: "Yoğurdu tencereye eklerken kaynar çorbadan birkaç kaşık yoğurda katıp yavaş yavaş alıştırırsanız kesilmez.",
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    ingredients: [
      { name: "yoğurt", amount: 2, unit: "su bardağı", scalable: true },
      { name: "pirinç", amount: 3, unit: "yemek kaşığı", scalable: true },
      { name: "yumurta", amount: 1, unit: "adet", scalable: true },
      { name: "un", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "su", amount: 5, unit: "su bardağı", scalable: true },
      { name: "tereyağı", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "kurutulmuş nane", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "tuz", amount: 1, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Pirinci yıkayıp suyla birlikte tencereye alın, yumuşayana kadar 15 dakika haşlayın.",
      "Ayrı bir kapta yoğurt, yumurta ve unu çırpın; kaynar sudan birkaç kaşık ekleyip yoğurdu ısıya alıştırın.",
      "Yoğurt karışımını yavaşça pirinçli suya ekleyip sürekli karıştırarak kaynatın (kesilmemesi için kaynadıktan sonra 5 dk kısık ateşte pişirin).",
      "Tuzunu ekleyin. Ayrı bir tavada tereyağını eritip naneyi kavurun, çorbanın üzerine gezdirerek servis edin.",
    ],
  },

  // ---- ANA YEMEK ----
  {
    category: "Ana Yemek",
    title: "Karnıyarık",
    summary: "Kıymayla doldurulmuş, fırında pişirilen klasik patlıcan yemeği.",
    tip: "Patlıcanları kızartmadan önce tuzlu suda bekletirseniz daha az yağ çeker.",
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 40,
    ingredients: [
      { name: "patlıcan", amount: 4, unit: "adet", scalable: true },
      { name: "kıyma", amount: 300, unit: "gram", scalable: true },
      { name: "soğan", amount: 1, unit: "adet", scalable: true },
      { name: "domates", amount: 2, unit: "adet", scalable: true },
      { name: "yeşil biber", amount: 2, unit: "adet", scalable: true },
      { name: "sarımsak", amount: 2, unit: "diş", scalable: true },
      { name: "salça (domates)", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "sıvı yağ (kızartmak için)", amount: 3, unit: "su bardağı", scalable: false },
      { name: "tuz", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "karabiber", amount: 0.5, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Patlıcanları soyarak zebra desenli soyun, tuzlu suda 15 dakika bekletip kurulayın.",
      "Bol yağda her tarafını hafif kızartın, kağıt havluya alıp yağını süzdürün.",
      "Soğan ve sarımsağı kavurun, kıymayı ekleyip rengi dönene kadar pişirin.",
      "Doğranmış domates, biber, salça, tuz ve karabiberi ekleyip 8-10 dakika pişirin (iç harç).",
      "Patlıcanları fırın kabına dizin, ortalarını hafifçe yarıp iç harcı doldurun.",
      "Üzerlerine ince domates ve biber dilimleri koyup 180°C fırında 20-25 dakika pişirin.",
    ],
  },
  {
    category: "Ana Yemek",
    title: "Kuru Fasulye",
    summary: "Etli ve salçalı, pilav ile klasik ikili olan Türk mutfağının vazgeçilmezi.",
    tip: "Fasulyeyi bir gece önceden suda bekletirseniz pişme süresi kısalır ve daha kolay sindirilir.",
    servings: 5,
    prepMinutes: 15,
    cookMinutes: 60,
    ingredients: [
      { name: "kuru fasulye", amount: 2.5, unit: "su bardağı", scalable: true },
      { name: "kuşbaşı et veya sosis", amount: 200, unit: "gram", scalable: true },
      { name: "soğan", amount: 1, unit: "adet", scalable: true },
      { name: "salça (domates)", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "sıvı yağ", amount: 3, unit: "yemek kaşığı", scalable: true },
      { name: "su", amount: 5, unit: "su bardağı", scalable: true },
      { name: "tuz", amount: 1.5, unit: "çay kaşığı", scalable: true },
      { name: "pul biber", amount: 1, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Kuru fasulyeyi bir gece önceden bol suda bekletin, suyunu süzün.",
      "Tencerede yağda soğanı kavurun, eti ekleyip rengi dönene kadar pişirin.",
      "Salçayı ekleyip 2 dakika kavurun, fasulyeyi ve suyu ilave edin.",
      "Kapağı kapatıp fasulye yumuşayana kadar (40-50 dk) kısık ateşte pişirin, gerekirse su ekleyin.",
      "Son 10 dakikada tuz ve pul biberi ekleyin. Pilav ile sıcak servis edin.",
    ],
  },
  {
    category: "Ana Yemek",
    title: "Izgara Tavuk Şiş",
    summary: "Marine edilip ızgarada pişirilen, sulu ve lezzetli tavuk şiş.",
    tip: "Tavuğu en az 2 saat, mümkünse bir gece önceden marine ederseniz çok daha lezzetli olur.",
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    ingredients: [
      { name: "tavuk göğsü (kuşbaşı)", amount: 600, unit: "gram", scalable: true },
      { name: "yoğurt", amount: 3, unit: "yemek kaşığı", scalable: true },
      { name: "zeytinyağı", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "sarımsak", amount: 2, unit: "diş", scalable: true },
      { name: "kırmızı biber salçası", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "kekik", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "tuz", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "karabiber", amount: 0.5, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Yoğurt, zeytinyağı, ezilmiş sarımsak, salça, kekik, tuz ve karabiberi karıştırıp marinasyon sosunu hazırlayın.",
      "Tavuk parçalarını sosla iyice harmanlayıp en az 2 saat buzdolabında bekletin.",
      "Marine edilmiş tavukları şişlere dizin.",
      "Önceden ısıtılmış ızgara veya tavada her tarafı pişene kadar (12-15 dk) çevirerek pişirin.",
      "Sıcak servis edin.",
    ],
  },

  // ---- SALATALAR ----
  {
    category: "Salatalar",
    title: "Çoban Salata",
    summary: "Domates, salatalık ve biberle yapılan taze, ferah bir salata.",
    tip: "Sebzeleri servisten hemen önce kesip tuzlayın, erken tuzlarsanız suyunu bırakır.",
    servings: 4,
    prepMinutes: 12,
    cookMinutes: 0,
    ingredients: [
      { name: "domates", amount: 3, unit: "adet", scalable: true },
      { name: "salatalık", amount: 2, unit: "adet", scalable: true },
      { name: "yeşil biber", amount: 2, unit: "adet", scalable: true },
      { name: "soğan (isteğe bağlı)", amount: 0.5, unit: "adet", scalable: true },
      { name: "maydanoz", amount: 3, unit: "yemek kaşığı", scalable: true },
      { name: "zeytinyağı", amount: 3, unit: "yemek kaşığı", scalable: true },
      { name: "limon suyu", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "tuz", amount: 0.5, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Domates, salatalık ve biberi küçük küpler halinde doğrayın.",
      "İnce doğranmış soğan ve maydanozu ekleyin.",
      "Zeytinyağı, limon suyu ve tuzu ekleyip hafifçe karıştırın.",
      "Hemen servis edin.",
    ],
  },
  {
    category: "Salatalar",
    title: "Gavurdağı Salatası",
    summary: "Cevizli, nar ekşili, Güneydoğu mutfağından baharatlı bir domates salatası.",
    tip: "Cevizleri kızartmadan hafifçe kavurursanız aroması belirginleşir.",
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 0,
    ingredients: [
      { name: "domates", amount: 4, unit: "adet", scalable: true },
      { name: "soğan", amount: 1, unit: "adet", scalable: true },
      { name: "yeşil biber", amount: 2, unit: "adet", scalable: true },
      { name: "ceviz içi", amount: 0.5, unit: "su bardağı", scalable: true },
      { name: "maydanoz", amount: 3, unit: "yemek kaşığı", scalable: true },
      { name: "nar ekşisi", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "zeytinyağı", amount: 3, unit: "yemek kaşığı", scalable: true },
      { name: "pul biber", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "tuz", amount: 0.5, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Domatesleri küçük küpler halinde doğrayın, soğanı ince ince kıyın.",
      "Biberleri küçük parçalara bölün, cevizleri kabaca kırın.",
      "Tüm malzemeleri geniş bir kapta birleştirin.",
      "Nar ekşisi, zeytinyağı, pul biber ve tuzu ekleyip iyice karıştırın.",
      "Üzerine maydanoz serperek servis edin.",
    ],
  },
  {
    category: "Salatalar",
    title: "Mevsim Salata",
    summary: "Marul, roka ve renkli sebzelerle yapılan hafif, doyurucu bir salata.",
    tip: "Yeşillikleri sostan hemen önce karıştırın, önceden sosladığınızda pörsür.",
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 0,
    ingredients: [
      { name: "marul", amount: 0.5, unit: "adet", scalable: true },
      { name: "roka", amount: 1, unit: "demet", scalable: true },
      { name: "havuç", amount: 1, unit: "adet", scalable: true },
      { name: "mısır (haşlanmış)", amount: 0.5, unit: "su bardağı", scalable: true },
      { name: "kırmızı lahana", amount: 1, unit: "su bardağı", scalable: true },
      { name: "zeytinyağı", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "limon suyu", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "tuz", amount: 0.5, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Marul ve rokayı yıkayıp iri parçalar halinde doğrayın.",
      "Havucu ve kırmızı lahanayı rendeleyin veya ince ince doğrayın.",
      "Tüm sebzeleri ve mısırı geniş bir kapta birleştirin.",
      "Zeytinyağı, limon suyu ve tuzu servisten hemen önce ekleyip karıştırın.",
    ],
  },

  // ---- TATLILAR ----
  {
    category: "Tatlılar",
    title: "Sütlaç",
    summary: "Fırında üzeri kızarmış, kremamsı klasik Türk sütlacı.",
    tip: "Pirinci sütle pişirmeden önce az suyla haşlarsanız daha kısa sürede kıvam alır.",
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 50,
    ingredients: [
      { name: "pirinç", amount: 0.5, unit: "su bardağı", scalable: true },
      { name: "süt", amount: 5, unit: "su bardağı", scalable: true },
      { name: "şeker", amount: 1, unit: "su bardağı", scalable: true },
      { name: "su", amount: 1, unit: "su bardağı", scalable: true },
      { name: "nişasta", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "vanilya", amount: 1, unit: "paket", scalable: false },
    ],
    steps: [
      "Pirinci yıkayıp su ile birlikte yumuşayana kadar (15 dk) haşlayın.",
      "Sütü ekleyip kaynatın, kısık ateşte 20 dakika pişirin.",
      "Nişastayı biraz soğuk suyla açıp karışıma ekleyin, sürekli karıştırarak kıvam alana kadar pişirin.",
      "Şeker ve vanilyayı ekleyip 5 dakika daha pişirin.",
      "Kaselere paylaştırıp 200°C fırında üzeri hafif kızarana kadar (10-15 dk) pişirin, soğutup servis edin.",
    ],
  },
  {
    category: "Tatlılar",
    title: "Kazandibi",
    summary: "Altı hafifçe karamelize olmuş, süt bazlı geleneksel bir tatlı.",
    tip: "Karamelizasyon aşamasında tavayı sabit ısıda tutup sık sık kontrol edin, yanmasını önlersiniz.",
    servings: 6,
    prepMinutes: 15,
    cookMinutes: 30,
    ingredients: [
      { name: "süt", amount: 5, unit: "su bardağı", scalable: true },
      { name: "şeker", amount: 1, unit: "su bardağı", scalable: true },
      { name: "nişasta", amount: 4, unit: "yemek kaşığı", scalable: true },
      { name: "pirinç unu", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "tereyağı", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "vanilya", amount: 1, unit: "paket", scalable: false },
    ],
    steps: [
      "Nişasta ve pirinç ununu bir miktar soğuk sütle pürüzsüz olana kadar karıştırın.",
      "Kalan sütü ve şekeri tencereye alıp kaynatın.",
      "Nişasta karışımını ekleyip sürekli karıştırarak koyulaşana kadar pişirin.",
      "Tereyağı ve vanilyayı ekleyip karıştırın.",
      "Yağlanmış tepsiye dökün, altı hafif kızarana kadar altlı üstlü ocakta veya fırında pişirin, soğutup dilimleyerek servis edin.",
    ],
  },
  {
    category: "Tatlılar",
    title: "Revani",
    summary: "İrmikli, şerbetli, hafif limon aromalı klasik tatlımız.",
    tip: "Sıcak revaniye soğuk şerbet (veya tam tersi) dökerseniz daha iyi emilim sağlarsınız.",
    servings: 8,
    prepMinutes: 15,
    cookMinutes: 35,
    ingredients: [
      { name: "irmik", amount: 1, unit: "su bardağı", scalable: true },
      { name: "un", amount: 1, unit: "su bardağı", scalable: true },
      { name: "şeker", amount: 1, unit: "su bardağı", scalable: true },
      { name: "yoğurt", amount: 1, unit: "su bardağı", scalable: true },
      { name: "sıvı yağ", amount: 0.5, unit: "su bardağı", scalable: true },
      { name: "yumurta", amount: 3, unit: "adet", scalable: true },
      { name: "kabartma tozu", amount: 1, unit: "paket", scalable: false },
      { name: "şerbet için su", amount: 3, unit: "su bardağı", scalable: true },
      { name: "şerbet için şeker", amount: 2.5, unit: "su bardağı", scalable: true },
      { name: "limon suyu", amount: 1, unit: "yemek kaşığı", scalable: true },
    ],
    steps: [
      "Yumurta ve şekeri çırpın, yoğurt ve sıvı yağı ekleyip karıştırın.",
      "İrmik, un ve kabartma tozunu eleyerek ekleyin, pürüzsüz bir hamur elde edin.",
      "Yağlanmış fırın tepsisine dökün, 180°C fırında üzeri kızarana kadar (30-35 dk) pişirin.",
      "Pişerken şerbeti hazırlayın: su ve şekeri kaynatıp 5 dakika kaynattıktan sonra limon suyunu ekleyip ocaktan alın.",
      "Fırından çıkan sıcak revaniye ılık şerbeti yavaşça gezdirerek dökün, dilimleyip servis edin.",
    ],
  },

  // ---- HAMUR İŞİ ----
  {
    category: "Hamur İşi",
    title: "Su Böreği",
    summary: "Katlı, peynirli, fırında pişirilen klasik Türk böreği.",
    tip: "Yufkaları kaynar suda haşlarken birbirine yapışmaması için tek tek, hızlıca daldırıp çıkarın.",
    servings: 8,
    prepMinutes: 40,
    cookMinutes: 35,
    ingredients: [
      { name: "yufka", amount: 6, unit: "adet", scalable: true },
      { name: "beyaz peynir", amount: 250, unit: "gram", scalable: true },
      { name: "maydanoz", amount: 3, unit: "yemek kaşığı", scalable: true },
      { name: "yumurta", amount: 2, unit: "adet", scalable: true },
      { name: "süt", amount: 1.5, unit: "su bardağı", scalable: true },
      { name: "sıvı yağ", amount: 0.5, unit: "su bardağı", scalable: true },
      { name: "tereyağı (üzeri için)", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "tuz", amount: 0.5, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Peyniri ufalayıp maydanozla karıştırın, iç harcı hazırlayın.",
      "Yumurta, süt, sıvı yağ ve tuzu çırparak harcı hazırlayın.",
      "Geniş bir tencerede su kaynatın; yufkaları teker teker 20-30 saniye haşlayıp soğuk suya alın, süzün.",
      "Yağlanmış fırın tepsisine yufkaları harca batırarak dizin, yarısına iç harcı serpin.",
      "Kalan yufkaları da aynı şekilde üzerine dizip son yufkayı kapatın.",
      "Üzerine eritilmiş tereyağı gezdirip 180°C fırında üzeri altın rengi olana kadar (30-35 dk) pişirin.",
    ],
  },
  {
    category: "Hamur İşi",
    title: "Poğaça",
    summary: "Yumuşacık, peynirli, mayasız hazırlanan pratik poğaça.",
    tip: "Hamuru yoğururken fazla un eklemeyin, hafif yapışkan kalması poğaçaları yumuşak yapar.",
    servings: 12,
    prepMinutes: 25,
    cookMinutes: 25,
    ingredients: [
      { name: "un", amount: 4, unit: "su bardağı", scalable: true },
      { name: "yoğurt", amount: 1, unit: "su bardağı", scalable: true },
      { name: "sıvı yağ", amount: 0.5, unit: "su bardağı", scalable: true },
      { name: "tereyağı (oda sıcaklığında)", amount: 100, unit: "gram", scalable: true },
      { name: "yumurta", amount: 1, unit: "adet", scalable: true },
      { name: "kabartma tozu", amount: 1, unit: "paket", scalable: false },
      { name: "tuz", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "beyaz peynir (iç harç)", amount: 200, unit: "gram", scalable: true },
      { name: "yumurta sarısı (üzeri için)", amount: 1, unit: "adet", scalable: false },
      { name: "çörek otu (üzeri için)", amount: 1, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Yoğurt, sıvı yağ, tereyağı, yumurta, tuz ve kabartma tozunu bir kapta karıştırın.",
      "Unu azar azar ekleyip yumuşak, hafif yapışkan bir hamur yoğurun.",
      "Hamurdan ceviz büyüklüğünde parçalar koparıp içine peynir koyarak yuvarlayın.",
      "Yağlı kağıt serili tepsiye dizin, üzerlerine yumurta sarısı sürüp çörek otu serpin.",
      "180°C fırında üzeri altın rengi olana kadar (20-25 dk) pişirin.",
    ],
  },
  {
    category: "Hamur İşi",
    title: "Kıymalı Pide",
    summary: "İnce hamurlu, bol kıymalı, fırında pişirilen kayık şeklinde pide.",
    tip: "Pideyi fırına vermeden önce tepsiyi de fırınla birlikte ısıtırsanız alt yüzü daha çıtır olur.",
    servings: 4,
    prepMinutes: 60,
    cookMinutes: 20,
    ingredients: [
      { name: "un", amount: 3, unit: "su bardağı", scalable: true },
      { name: "yaş maya", amount: 20, unit: "gram", scalable: true },
      { name: "ılık su", amount: 1, unit: "su bardağı", scalable: true },
      { name: "şeker", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "tuz", amount: 1, unit: "çay kaşığı", scalable: true },
      { name: "sıvı yağ", amount: 2, unit: "yemek kaşığı", scalable: true },
      { name: "kıyma", amount: 300, unit: "gram", scalable: true },
      { name: "soğan", amount: 1, unit: "adet", scalable: true },
      { name: "domates", amount: 1, unit: "adet", scalable: true },
      { name: "yeşil biber", amount: 1, unit: "adet", scalable: true },
      { name: "salça (domates)", amount: 1, unit: "yemek kaşığı", scalable: true },
      { name: "yumurta sarısı (üzeri için)", amount: 1, unit: "adet", scalable: false },
    ],
    steps: [
      "Mayayı ılık suda şekerle eritin, 5 dakika bekletin.",
      "Un, tuz ve sıvı yağı ekleyip yumuşak bir hamur yoğurun; üzerini örtüp 45 dakika mayalanmaya bırakın.",
      "Kıyma, rendelenmiş soğan, doğranmış domates, biber ve salçayı karıştırıp iç harcı hazırlayın.",
      "Mayalanan hamuru 4 parçaya bölüp oval şekilde açın, kenarlarını kıvırıp kayık formu verin.",
      "İç harcı ortasına yayıp 220°C önceden ısıtılmış fırında 15-20 dakika pişirin.",
      "Kenarlarına isteğe bağlı yumurta sarısı sürebilirsiniz, sıcak servis edin.",
    ],
  },

  // ---- İÇECEKLER ----
  {
    category: "İçecekler",
    title: "Ayran",
    summary: "Yoğurt, su ve tuzla hazırlanan geleneksel Türk içeceği.",
    tip: "Ayranı blenderdan geçirirseniz köpüklü ve daha kıvamlı olur.",
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 0,
    ingredients: [
      { name: "yoğurt", amount: 2, unit: "su bardağı", scalable: true },
      { name: "soğuk su", amount: 2, unit: "su bardağı", scalable: true },
      { name: "tuz", amount: 0.5, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Yoğurdu geniş bir kaba alıp çırpın.",
      "Soğuk suyu azar azar ekleyerek çırpmaya devam edin.",
      "Tuzu ekleyip iyice karıştırın veya blenderdan geçirin.",
      "Buzla birlikte soğuk servis edin.",
    ],
  },
  {
    category: "İçecekler",
    title: "Türk Kahvesi",
    summary: "Cezvede pişirilen, köpüklü geleneksel Türk kahvesi.",
    tip: "Kahveyi pişirirken kısık ateşte, sabırla pişirmek köpüğün oturmasını sağlar.",
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 5,
    ingredients: [
      { name: "Türk kahvesi", amount: 1, unit: "kahve fincanı ölçeği", scalable: true },
      { name: "su", amount: 1, unit: "kahve fincanı", scalable: true },
      { name: "şeker (isteğe bağlı)", amount: 1, unit: "çay kaşığı", scalable: true },
    ],
    steps: [
      "Cezveye su, kahve ve istenirse şekeri ekleyip karıştırın (kaynamadan önce).",
      "Kısık ateşte, karıştırmadan yavaşça ısıtın.",
      "Köpük oluşmaya başlayınca köpüğü fincana alın, cezveyi tekrar ocağa koyup kaynatın.",
      "Kaynayınca fincana yavaşça dökün, sıcak servis edin.",
    ],
  },
  {
    category: "İçecekler",
    title: "Ev Yapımı Limonata",
    summary: "Taze sıkılmış limonla hazırlanan ferahlatıcı bir yaz içeceği.",
    tip: "Limon kabuğunu az miktarda rendeleyip şerbete katarsanız aroması belirginleşir.",
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
    ingredients: [
      { name: "limon", amount: 4, unit: "adet", scalable: true },
      { name: "şeker", amount: 0.75, unit: "su bardağı", scalable: true },
      { name: "su", amount: 4, unit: "su bardağı", scalable: true },
      { name: "nane yaprağı (isteğe bağlı)", amount: 5, unit: "adet", scalable: true },
    ],
    steps: [
      "Limonları sıkıp suyunu süzün.",
      "Şekeri az miktarda ılık suda eritin.",
      "Limon suyu, şeker şurubu ve kalan suyu geniş bir sürahide karıştırın.",
      "Buz ve nane yapraklarıyla soğuk servis edin.",
    ],
  },
];
